spack:
  view: /opt/view
  config:
    install_tree:
      root: /opt/spack
      padded_length: 128

  packages:
    all:
      require:
      - target=x86_64_v3
    gcc:
      externals:
      - spec: gcc@13.3.0 languages:='c,c++,fortran'
        prefix: /usr
        extra_attributes:
          compilers:
            c: /usr/bin/gcc
            cxx: /usr/bin/g++
            fortran: /usr/bin/gfortran
    cuda:
      buildable: false
      externals:
      - spec: cuda@12.9.0
        prefix: /usr/local/cuda
    llvm-amdgpu:
      externals:
      - spec: llvm-amdgpu@6.4.1
        prefix: /opt/rocm/llvm/
        extra_attributes:
          compilers:
            c: /usr/bin/amdclang
            cxx: /usr/bin/amdclang++
      buildable: false
    hip:
      buildable: false
      externals:
      - spec: hip@6.4.1
        prefix: /opt/rocm
    hsa-rocr-dev:
      buildable: false
      externals:
      - spec: hsa-rocr-dev@6.4.1
        prefix: /opt/rocm
    comgr:
      buildable: false
      externals:
      - spec: comgr@6.4.1
        prefix: /opt/rocm
    hipsparse:
      buildable: false
      externals:
      - spec: hipsparse@6.4.1
        prefix: /opt/rocm
    hipblas:
      buildable: false
      externals:
      - spec: hipblas@6.4.1
        prefix: /opt/rocm/
    rocblas:
      buildable: false
      externals:
      - spec: rocblas@6.4.1
        prefix: /opt/rocm
    rocprim:
      buildable: false
      externals:
      - spec: rocprim@6.4.1
        prefix: /opt/rocm
    rocthrust:
      buildable: false
      externals:
      - spec: rocthrust@6.4.1
        prefix: /opt/rocm
    rocm-core:
      buildable: false
      externals:
      - spec: rocm-core@6.4.1
        prefix: /opt/rocm
    rocm-cmake:
      buildable: false
      externals:
      - spec: rocm-cmake@6.4.1
        prefix: /opt/rocm

  mirrors:
    local-buildcache:
      url: oci://ghcr.io/ukri-bench/spack-buildcache
      binary: true
      signed: false
      access_pair:
        id_variable: GITHUB_USER
        secret_variable: GITHUB_TOKEN
